### ISSUE TITLE
Cordova打包报错

### ISSUE THREAD

**Issue by zhemgshibo** [hewz/cordova-baidu-location#13]
你好：
        当使用你集成的最新版的百度地图Android版定位SDK（v7.2）版本时，对应的Cordova封包时会报错。错误如下：
`:compileDebugJavaWithJavac

:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no p                                                                                                                                                                                               revious execution, etc.).
D:\truck\ionic-demo\platforms\android\src\com\hewz\plugins\baidu\BaiduLocation.java:95: ����: �������Ḳ�ǻ�ʵ�ֳ����͵ķ���
        @Override
        ^
ע: ĳЩ�����ļ�ʹ�û򸲸����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
ע: ĳЩ�����ļ�ʹ����δ�������򲻰�ȫ�Ĳ�����
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:unchecked ���±��롣
1 ������
:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 43.448 secs
Error: cmd: Command failed with exit code 1 Error output:
D:\truck\ionic-demo\platforms\android\src\com\hewz\plugins\baidu\BaiduLocation.java:95: ����: �������Ḳ�ǻ�ʵ�ֳ����͵ķ���
        @Override
        ^
ע: ĳЩ�����ļ�ʹ�û򸲸����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
ע: ĳЩ�����ļ�ʹ����δ�������򲻰�ȫ�Ĳ�����
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:unchecked ���±��롣
1 ������

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.`

报错的地方是BaiduLocation.java第95行，看代码怀疑是引用的BaiduLBS_Android.jar中BDLocationListener类的方法发生变化。

还有如果能够找到之前的版本，希望能够给上一个版本打一个版本号的话，这样的话便于使用。
总之，感谢你封装的插件，给我省了不少事情。谢谢了

**Comment by hewz** [comment]
baidu removed a function in the latest sdk, but mentioned nothing in the doc.

**Comment by zhemgshibo** [comment]
这个问题已经解决了。
