### ISSUE TITLE
Error: Failed to fetch plugin

### ISSUE THREAD

**Issue by deepbluev5** [hewz/cordova-baidu-location#17]
i run the command in ubuntu:
**cordova plugin add https://github.com/hewz/cordova-baidu-location --variable API_KEY="myKEY"**
it shows:

    Error: Failed to fetch plugin 
    https://github.com/hewz/cordova-baidu-location via registry.
    Probably this is either a connection problem, or plugin spec is 
    incorrect.
    Check your connection and plugin name/version/URL.
    Failed to get absolute path to installed module

what should i do ?

**Comment by hewz** [comment]
Check your connection or download the zip file and install the plugin locally.

**Comment by deepbluev5** [comment]
thanks 
i try :
**cordova plugin file://path/to/plugin --variable API_KEY="my_KEY"** before your reply 
but fail to work
it works as:
**cordova plugin /path/to/plugin --variable API_KEY="my_KEY"**
