### ISSUE TITLE
安装的插件，build的时候没有添加到android项目里

### ISSUE THREAD

**Issue by lewis-geek** [hewz/cordova-baidu-location#4]
找不到baidu_location，同时在android目录里也看不到插件的文件夹

**Comment by zhengjin** [comment]
我在如下目录“platforms\android\platform_www\plugins\com.hewz.plugins.baidu.location\www”
看到了插件的JS，但是还是提示“baidu_location is not defined”
和我用Angularjs有关系？

**Comment by hewz** [comment]
@zhengjin 应用启动时调用的吗？可能是cordova插件还没加载完，可以设一个timeout试试。
