### ISSUE TITLE
不知道为啥项目刚进来调用的时候有时候获取不到定位，再次点击定位按钮的时候就可以

### ISSUE THREAD

**Issue by itshu** [hewz/cordova-baidu-location#6]
是我加载的顺序有关吗。ionViewDidLoad的时候加载的，还望指教

**Comment by hewz** [comment]
@itshu 
把Java文件中这几句注释掉试试。
PluginResult pluginResult = new PluginResult(PluginResult.Status.NO_RESULT);
pluginResult.setKeepCallback(true);
cbCtx.sendPluginResult(pluginResult);

fixed in the latest commit..
