### ISSUE TITLE
Android7.1.1，WiFi获取到的address为null

### ISSUE THREAD

**Issue by spzhao** [hewz/cordova-baidu-location#7]
Android7.1.1，WiFi获取到的address为null
需要执行两次才能获取到定位信息
修改需要获取位置为TRUE可以获取到地理位置
option.setIsNeedAddress(true);

**Comment by hewz** [comment]
应该跟这个是一个问题 #6 把这几句注释掉试试。可能是忘了删除的多余代码。
PluginResult pluginResult = new PluginResult(PluginResult.Status.NO_RESULT);
pluginResult.setKeepCallback(true);
cbCtx.sendPluginResult(pluginResult);
