### ISSUE TITLE
ionic3 安装失败

### ISSUE THREAD

**Issue by ducp123** [hewz/cordova-baidu-location#8]
0 info it worked if it ends with ok
1 verbose cli [ 'E:\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\xxx\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'https://github.com/hewz/cordova-baidu-location',
1 verbose cli   '--save' ]
2 info using npm@5.3.0
3 info using node@v6.9.5
4 verbose npm-session 
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for git+https://github.com/hewz/cordova-baidu-location.git Command failed: C:\Program Files\Git\cmd\git.EXE submodule update -q --init --recursive
7 silly fetchPackageMetaData C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 7: basename: command not found
7 silly fetchPackageMetaData C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 7: sed: command not found
7 silly fetchPackageMetaData C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 19: .: git-sh-setup: file not found
8 verbose stack Error: Command failed: C:\Program Files\Git\cmd\git.EXE submodule update -q --init --recursive
8 verbose stack C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 7: basename: command not found
8 verbose stack C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 7: sed: command not found
8 verbose stack C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 19: .: git-sh-setup: file not found
8 verbose stack
8 verbose stack     at ChildProcess.exithandler (child_process.js:206:12)
8 verbose stack     at emitTwo (events.js:106:13)
8 verbose stack     at ChildProcess.emit (events.js:191:7)
8 verbose stack     at maybeClose (internal/child_process.js:877:16)
8 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
9 verbose cwd C:\Users\Roronoazoro\lj3\node_modules
10 verbose Windows_NT 10.0.15063
11 verbose argv "E:\\nodejs\\node.exe" "C:\\Users\\Roronoazoro\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/hewz/cordova-baidu-location" "--save"
12 verbose node v6.9.5
13 verbose npm  v5.3.0
14 error code 1
15 error Command failed: C:\Program Files\Git\cmd\git.EXE submodule update -q --init --recursive
15 error C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 7: basename: command not found
15 error C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 7: sed: command not found
15 error C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 19: .: git-sh-setup: file not found
16 verbose exit [ 1, true ]

**Comment by hewz** [comment]
Failed to reproduce in my ionic3 env

**Comment by ducp123** [comment]
那就是用不了？能完善吗？

**Comment by hewz** [comment]
我意思是说我本地未能复现你这个错误。而且你的错误日志里全是command not found，看起来像是环境没配好。

**Comment by ducp123** [comment]
好的，谢谢！但是之前ionic2得时候可以用，就只是升级了ionic3，其他基本没动过！

**Comment by ducp123** [comment]
OK，搞定了，GIT的原因，GIT 有点坑，默认安装后环境变量里面配置的路径是cmd下面的，换成bin下面的就OK了！谢谢楼主回复！
